import type { Transaction } from "./types.js";
import {
  calculateBlockHash,
    createBlock,
      type Block,
      } from "./block-builder.js";
      import {
        calculateMiningHash,
          MINING_DIFFICULTY,
            mineBlock,
            } from "../consensus/mining.js";
            import { validateTransaction } from "./transaction.js";

            export class Blockchain {
              private readonly chain: Block[] = [];

                constructor() {
                    const genesisBlock: Block = {
                          index: 0,
                                previousHash: "0",
                                      timestamp: Date.now(),
                                            transactions: [],
                                                  miner: "GENESIS",
                                                        reward: 0n,
                                                              nonce: 0,
                                                                    hash: "GENESIS",
                                                                        };

                                                                            this.chain.push(genesisBlock);
                                                                              }

                                                                                get latestBlock(): Block {
                                                                                    return this.chain[this.chain.length - 1]!;
                                                                                      }

                                                                                        get blocks(): readonly Block[] {
                                                                                            return this.chain;
                                                                                              }

                                                                                                addBlock(
                                                                                                    transactions: Transaction[],
                                                                                                        miner: string,
                                                                                                          ): Block {
                                                                                                              if (!miner) {
                                                                                                                    throw new Error("Miner address is required");
                                                                                                                        }

                                                                                                                            for (const transaction of transactions) {
                                                                                                                                  if (!validateTransaction(transaction)) {
                                                                                                                                          throw new Error("Invalid transaction");
                                                                                                                                                }
                                                                                                                                                    }

                                                                                                                                                        const block = createBlock(
                                                                                                                                                              this.latestBlock.index + 1,
                                                                                                                                                                    this.latestBlock.hash,
                                                                                                                                                                          transactions,
                                                                                                                                                                                miner,
                                                                                                                                                                                    );

                                                                                                                                                                                        const miningResult = mineBlock(
                                                                                                                                                                                              block,
                                                                                                                                                                                                    MINING_DIFFICULTY,
                                                                                                                                                                                                        );

                                                                                                                                                                                                            block.nonce = miningResult.nonce;
                                                                                                                                                                                                                block.hash = miningResult.hash;

                                                                                                                                                                                                                    this.chain.push(block);

                                                                                                                                                                                                                        return block;
                                                                                                                                                                                                                          }

                                                                                                                                                                                                                            isValid(): boolean {
                                                                                                                                                                                                                                if (this.chain.length === 0) {
                                                                                                                                                                                                                                      return false;
                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                              const genesis = this.chain[0]!;

                                                                                                                                                                                                                                                  if (
                                                                                                                                                                                                                                                        genesis.index !== 0 ||
                                                                                                                                                                                                                                                              genesis.previousHash !== "0" ||
                                                                                                                                                                                                                                                                    genesis.miner !== "GENESIS" ||
                                                                                                                                                                                                                                                                          genesis.reward !== 0n ||
                                                                                                                                                                                                                                                                                genesis.nonce !== 0 ||
                                                                                                                                                                                                                                                                                      genesis.hash !== "GENESIS"
                                                                                                                                                                                                                                                                                          ) {
                                                                                                                                                                                                                                                                                                return false;
                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                        for (let i = 1; i < this.chain.length; i++) {
                                                                                                                                                                                                                                                                                                              const current = this.chain[i]!;
                                                                                                                                                                                                                                                                                                                    const previous = this.chain[i - 1]!;

                                                                                                                                                                                                                                                                                                                          if (current.index !== previous.index + 1) {
                                                                                                                                                                                                                                                                                                                                  return false;
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                              if (current.previousHash !== previous.hash) {
                                                                                                                                                                                                                                                                                                                                                      return false;
                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                  if (
                                                                                                                                                                                                                                                                                                                                                                          !Number.isInteger(current.nonce) ||
                                                                                                                                                                                                                                                                                                                                                                                  current.nonce < 0
                                                                                                                                                                                                                                                                                                                                                                                        ) {
                                                                                                                                                                                                                                                                                                                                                                                                return false;
                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                            if (current.hash.length !== 64) {
                                                                                                                                                                                                                                                                                                                                                                                                                    return false;
                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                const expectedBlockHash = calculateBlockHash(
                                                                                                                                                                                                                                                                                                                                                                                                                                        current.index,
                                                                                                                                                                                                                                                                                                                                                                                                                                                current.previousHash,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        current.timestamp,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                current.transactions,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        current.miner,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                current.reward,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        current.nonce,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (current.hash !== expectedBlockHash) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const miningHash = calculateMiningHash(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                current,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        current.nonce,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (current.hash !== miningHash) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                !current.hash.startsWith(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "0".repeat(MINING_DIFFICULTY),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (const transaction of current.transactions) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!validateTransaction(transaction)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }